# Generated by Django 4.2.23 on 2025-08-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runway2', '0002_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='Video_Progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='Month_Progress',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='Year_Progress',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
