# Generated by Django 4.2.23 on 2025-09-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runway2', '0003_studentprogress_video_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='runway2.teacherprofile'),
        ),
    ]
