# Generated by Django 4.2.23 on 2025-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runway2', '0004_studentprogress_last_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
