# Generated by Django 4.2.23 on 2025-10-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runway2', '0005_studentprofile_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='Video_Hashes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
