# Generated by Django 4.2.23 on 2025-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runway2', '0006_studentprogress_video_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='Video_Hashes',
            field=models.JSONField(default=list),
        ),
    ]
